repository_type: pipeline

nf_core_version: 3.1.1

lint: {}

template:
  org: nf-core
  name: ontgeno
  description: Pipeline for genotype calling from ONT data
  author: Alexander Nater
  version: 1.0.0dev
  force: true
  outdir: .
  is_nfcore: true
